### ISSUE TITLE
Hit Button

### ISSUE THREAD

**Issue by timhilton** [timhilton/Blackjack#2]
User Story

As a user, I want to be able to click the hit button, so I can hit multiple times.

Test Statement

-When I click the hit button a second or third time... it should show the 4th and 5th cards

Context for problem

I'm not sure how to make it work a second and third time.

**Comment by amadden80** [comment]
Is this where that is?
```
function createHitButton(){
var container = $('section');
var hitButton = $('<button>');
hitButton.text('Hit');
container.append(hitButton);
hitButton.bind('click', function(e) {
     e.preventDefault();
     $('#card3').css({opacity: '1'});
     $('#playerCard3').css({opacity: '.2', backgroundColor: 'lightgrey'});
   });
};

```

I'm seeing you replace the 3rd card here, instead of maybe PUSHING a new card into an array?
Or appending a card to the dom?

**Comment by timhilton** [comment]
I figured it out...  :)  I had some reorganizing to do.  It involved appending a card to the DOM and rethinking my whole approach.  STOKED!

**Comment by emilylordahl** [comment]
Sweet!
