### ISSUE TITLE
Fold Button

### ISSUE THREAD

**Issue by timhilton** [timhilton/Blackjack#3]
User Story

As a user, I want to be able to hit the fold button, so I can restart the game
Test Statement

-When I hit the fold button it should revert to the original load of the game

Context for problem

when I'm trying to hit the fold button it redeals the deck but does not remove the cards shown by the hit button.
I have tried location reload - but that creates a flash on the screen as it just reloads the page.

There aren't any errors displaying, so the code is okay, it's about adding something new.

**Comment by amadden80** [comment]
add, commit, push      

Have you removed the existing dom elements?
This is a great reason why I like to have these parts generated via javascript.
Then you can just .remove() a dom node and then regenerate it using a function.
